library("plyr")

bhscenes_params <-
    list(list(n = 60, mu = 0),
         list(n = c(40, 20), mu = c(0, 3)),
         list(n = c(40, 20), mu = c(0, 2)),
         list(n = c(30, 30), mu = c(0, 1)),
         list(n = c(30, 30), mu = c(0, 0.5)),
         list(n = c(58, 2), mu = c(0, 3)),
         list(n = c(15, 30, 15), mu = c(0, 2, 0)),
         list(n = c(10, 40, 10), mu = c(0, 1, 0)),
         list(n = c(30, 20, 10), mu = c(0, 2, 0)),
         list(n = c(4, 1, 55), mu = c(0, 5, 0)),
         list(n = c(10, 15, 20, 15), mu = c(1, 0, 2, 1)),
         list(n = c(10, 10, 10, 30), mu = c(1, 2, 1, 0)),
         list(n = c(25, 1, 14, 20), mu = c(2, 0, 5, 3)),
         list(n = c(15, 5, 5, 35), mu = c(3, 0, 5, 3)),
         list(n = c(5, 5, 40, 5, 5), mu = c(0, 2, 0, 2, 0)),
         list(n = rep(12, 5), mu = c(0, 1, 0, 1, 0)),
         list(n = rep(12, 5), mu = 0:4),
         list(n = c(14, 5, 1, 1, 4, 9, 15, 11), mu = c(3, 5, 0, 2, 5, 2, 3, 4)),
         list(n = c(2, 14, 15, 15, 5, 1, 5, 3), mu = c(1, 0, 1, 4, 1, 5, 0, 1)),
         list(n = rep(6, 10), mu = rep(c(0, 2), 5)))

bhscene <- function(scene = 1, sigma = 1) {
  mapply(function(n, mu) rnorm(n, mu, sigma / n = bhscenes_params[[scene]][["n"]],
         mu = )
}

foo <- plyr::ldply(params, function(x, sigma) bhscene(x$n, x$mu, sigma), sigma = 1)

#' Generate Barry Hartigan (1993) Scenes
#'
#' In the original paper, \eqn{n = 60}, \eqn{\mu_0 = 0}, and \eqn{\sigma^2 = 1}.
#' Scenes were generated by randomly sampling \eqn{p \sim U(0, 1)}, and \eqn{w \sim U(0, 2)}.
bhscene <- function(n, p, mu0, w, sigma2) {
  breaks <- sample(c(0, 1), prob = c(1 - p, p), replace = TRUE)

}
